<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-73</name>
   <tag></tag>
   <elementGuidId>fe84a47d-881f-4de5-b3ff-4c37d7dbde05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-73']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#input-73</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>214a765b-ee1b-49b8-8195-bd7e9dd3f62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-73</value>
      <webElementGuid>b6cb39fe-527b-4310-95e6-f14940bbdddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>606ab4c6-40c5-48b6-b7fd-eb94f35aae0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-73&quot;)</value>
      <webElementGuid>85af41d0-da30-4cf5-bc59-27b6ea32e3ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-73']</value>
      <webElementGuid>05244d5e-81f1-4bd5-bef8-65ac07b3f247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[5]/div/div/div/input</value>
      <webElementGuid>cef7422a-3cb8-4e9a-b64d-7cf35d0d4579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>ce535b46-51a0-49f9-8255-b8f2d3f2f525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-73' and @type = 'text']</value>
      <webElementGuid>edd1da46-48a6-4bae-b40a-e07a1fc58d77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
