<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-46</name>
   <tag></tag>
   <elementGuidId>d672dac7-bd92-40fa-81e4-cb97c615812c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-46</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-46']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53388af7-d337-418c-8cdb-0aecb13c0fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-46</value>
      <webElementGuid>85d3204e-872d-453e-bbd1-ce44a1f0964e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edc13631-b36e-4841-9d9e-5eb58fb45f87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-46&quot;)</value>
      <webElementGuid>e1bc9463-4be2-44cc-a3e6-95a97d95b4c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-46']</value>
      <webElementGuid>898c375e-a862-4685-bd8a-2ce0d862fdba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div/div/div/div/input</value>
      <webElementGuid>87b09855-fe69-4eea-a000-d6bd3bd2fbbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ee9079c5-750f-44ac-af78-addb3dfc2b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-46' and @type = 'text']</value>
      <webElementGuid>05258add-8cb8-4df2-a322-eed4cc2391d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
