<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-55</name>
   <tag></tag>
   <elementGuidId>a8ac9b54-bf3a-4023-acf3-c1071fe2eec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-55</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-55']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b711a3ca-b23f-4324-a98a-2e02518e42dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-55</value>
      <webElementGuid>d975a80d-bae6-4334-88a7-7db1d2f3bdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9e0ca2a-914a-4c7f-87f6-4cb14b029f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-55&quot;)</value>
      <webElementGuid>0b709923-1ccd-4fdf-97b0-ad8650f6577d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-55']</value>
      <webElementGuid>7004fde6-3887-404f-83c2-1f49c5621121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[4]/div/div/div/input</value>
      <webElementGuid>7d075062-905f-4e5b-8a47-c0c19cd5bf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>c3a8d831-2f67-4eff-a3e4-972cebdd4d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-55' and @type = 'text']</value>
      <webElementGuid>98a767cc-aab9-4332-b84c-0ec08c0a88c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
