<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input-49</name>
   <tag></tag>
   <elementGuidId>528bca3c-068d-49ea-91aa-a576d0e6688e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-49</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-49']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00fe0a37-0332-4035-ae31-12833f3a194f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-49</value>
      <webElementGuid>5c2222e3-c2b4-4d34-b8b7-5e483264b6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7c9b5003-3eab-4dcb-a506-ba81f3b7db4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-49&quot;)</value>
      <webElementGuid>eaac7918-a5c6-4b52-90be-311809e6c432</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-49']</value>
      <webElementGuid>adaef658-406b-4312-971d-2eb4604249cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>d9449137-f77d-4ad4-8daf-15a0d325a869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>c1f6f90d-02ef-4ca5-b08e-379ab37a3f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-49' and @type = 'password']</value>
      <webElementGuid>f0615add-3e9e-4e89-8cca-a86dcf78f897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
